export const LOAD_CAMPAIGNS = 'LOAD_CAMPAIGNS';
export const LOAD_CAMPAIGN = 'LOAD_CAMPAIGN';
export const DELETE_CAMPAIGN = 'DELETE_CAMPAIGN';
export const CREATE_CAMPAIGN = 'CREATE_CAMPAIGN';
export const UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN';
